import mongoose from "mongoose";
import dotenv from "dotenv";

import District from "../models/District.js";
import City from "../models/City.js";

dotenv.config();

//////////////////////////////////////////////////////////////
// NORMALIZE
//////////////////////////////////////////////////////////////

const normalize = (str) =>
  str?.toLowerCase().replace(/[^a-z0-9]/g, "") || "";

//////////////////////////////////////////////////////////////
// DB CONNECT
//////////////////////////////////////////////////////////////

const connectDB = async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("✅ DB Connected");
};

//////////////////////////////////////////////////////////////
// MAIN
//////////////////////////////////////////////////////////////

const generateHQCities = async () => {
  try {
    //////////////////////////////////////////////////////////
    // FETCH DATA (NO N+1)
    //////////////////////////////////////////////////////////

    const [districts, cities] = await Promise.all([
      District.find({ isDeleted: false }),
      City.find({ isDeleted: false }),
    ]);

    //////////////////////////////////////////////////////////
    // BUILD MAPS
    //////////////////////////////////////////////////////////

    const cityMap = new Map(); // district+name → city
    const districtCityMap = new Map(); // district → all cities

    cities.forEach((c) => {
      if (!c.districtRef) return;

      const dId = String(c.districtRef);
      const norm = c.normalizedName;

      if (norm) {
        cityMap.set(dId + "_" + norm, c);
      }

      if (!districtCityMap.has(dId)) {
        districtCityMap.set(dId, []);
      }

      districtCityMap.get(dId).push(c);
    });

    //////////////////////////////////////////////////////////
    // BULK OPS
    //////////////////////////////////////////////////////////

    const bulkInsert = [];
    const bulkUpdate = [];

    let created = 0;
    let promoted = 0;
    let skipped = 0;
    let noGeo = 0;

    for (const district of districts) {
      const dId = String(district._id);
      const name = district.hqCityName?.trim() || district.name?.trim();

      if (!name) continue;

      const normalized = normalize(name);
      const key = dId + "_" + normalized;

      const existingCity = cityMap.get(key);

      ////////////////////////////////////////////////////////
      // CASE 1: EXACT CITY EXISTS → PROMOTE
      ////////////////////////////////////////////////////////

      if (existingCity) {
        if (!existingCity.isDistrictHQ) {
          bulkUpdate.push({
            updateOne: {
              filter: { _id: existingCity._id },
              update: {
                $set: {
                  isDistrictHQ: true,
                  isAutoGenerated: false,
                },
              },
            },
          });

          console.log(`🔁 PROMOTED: ${name}`);
          promoted++;
        } else {
          skipped++;
        }

        continue;
      }

      ////////////////////////////////////////////////////////
      // CASE 2: DISTRICT HAS OTHER CITY → PROMOTE FIRST
      ////////////////////////////////////////////////////////

      const districtCities = districtCityMap.get(dId);

      // ✅ CHECK HERE (NOT ABOVE)
      const existingDistrictHQ = districtCities?.find(c => c.isDistrictHQ);

      if (existingDistrictHQ) {
      
        // 🔥 CLEANUP: multiple HQ fix
        const otherHQs = districtCities.filter(
          (c) =>
            c.isDistrictHQ &&
            String(c._id) !== String(existingDistrictHQ._id)
        );

        if (otherHQs.length > 0) {
          bulkUpdate.push({
            updateMany: {
              filter: {
                _id: { $in: otherHQs.map((c) => c._id) },
              },
              update: {
                $set: { isDistrictHQ: false },
              },
            },
          });
        
          console.log(`🧹 CLEANED EXTRA HQs: ${name}`);
        }

        skipped++;
        continue;
      }


      if (districtCities && districtCities.length > 0) {
        const firstCity = districtCities.find(c => c.isServiceable) || districtCities[0];

        // ✅ IMPORTANT GUARD (ADD THIS)
        if (firstCity.isDistrictHQ) {
          skipped++;
          continue;
        }

        bulkUpdate.push({
          updateOne: {
            filter: { _id: firstCity._id },
            update: {
              $set: {
                isDistrictHQ: true,
              },
            },
          },
        });

        console.log(`🔁 PROMOTED (fallback): ${name}`);
        promoted++;
        continue;
      }

      ////////////////////////////////////////////////////////
      // CASE 3: CREATE HQ
      ////////////////////////////////////////////////////////

      const coords =
        district.geo?.coordinates &&
        district.geo.coordinates.length === 2
          ? district.geo.coordinates
          : null;

      if (!coords) {
        console.log(`⚠️ NO GEO: ${name}`);
        noGeo++;
        continue;
      }

      bulkInsert.push({
        insertOne: {
          document: {
            name,
            normalizedName: normalized,

            aliases: [],
            normalizedAliases: [],

            countryRef: district.countryRef,
            stateRef: district.stateRef,
            districtRef: district._id,

            isDistrictHQ: true,
            isServiceable: false,
            isAutoGenerated: true,

            cityType: "TIER3",

            geo: {
              type: "Point",
              coordinates: coords,
            },
          },
        },
      });

      cityMap.set(key, { normalizedName: normalized });

      console.log(`🔥 CREATE HQ: ${name}`);
    }

    //////////////////////////////////////////////////////////
    // EXECUTE BULK
    //////////////////////////////////////////////////////////

    if (bulkInsert.length > 0) {
      const res = await City.bulkWrite(bulkInsert, { ordered: false });
      created = res.insertedCount || 0;
    }

    if (bulkUpdate.length > 0) {
      await City.bulkWrite(bulkUpdate);
    }

    //////////////////////////////////////////////////////////
    // FINAL LOG
    //////////////////////////////////////////////////////////

    console.log("\n=======================");
    console.log(`🔥 Created: ${created}`);
    console.log(`🔁 Promoted: ${promoted}`);
    console.log(`⏭️ Skipped: ${skipped}`);
    console.log(`⚠️ No Geo: ${noGeo}`);
    console.log("=======================\n");

  } catch (error) {
    console.error("❌ ERROR:", error);
  } finally {
    await mongoose.disconnect();
    console.log("🔌 DB Disconnected");
  }
};

//////////////////////////////////////////////////////////////
// RUN
//////////////////////////////////////////////////////////////

connectDB().then(generateHQCities);