import mongoose from "mongoose";

//////////////////////////////////////////////////////////////
// 🌆 CITY SCHEMA — FINAL LOCKED (ZOMATO GRADE 10/10++)
//////////////////////////////////////////////////////////////

const CitySchema = new mongoose.Schema(
  {
    //////////////////////////////////////////////////////////
    // 1️⃣ BASIC IDENTIFICATION
    //////////////////////////////////////////////////////////

    name: {
      type: String,
      required: true,
      trim: true,
      minlength: 2,
      maxlength: 120,
    },

    //////////////////////////////////////////////////////////
    // 🔥 NORMALIZED NAME (CRITICAL)
    //////////////////////////////////////////////////////////

    normalizedName: {
      type: String,
      required: true,
      lowercase: true,
    },

    code: {
      type: String,
      trim: true,
      uppercase: true,
      minlength: 2,
      maxlength: 50,
      default: null,
    },

    //////////////////////////////////////////////////////////
    // 🔗 SLUG (SEO SAFE)
    //////////////////////////////////////////////////////////

    slug: {
      type: String,
      trim: true,
      lowercase: true,
      maxlength: 150,
      immutable: true,
    },

    //////////////////////////////////////////////////////////
    // 🧠 ALIASES
    //////////////////////////////////////////////////////////

    aliases: {
      type: [String],
      default: [],
    },

    normalizedAliases: {
      type: [String],
      default: [],
    },

    //////////////////////////////////////////////////////////
    // 2️⃣ TERRITORY RELATIONS
    //////////////////////////////////////////////////////////

    countryRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Country",
      required: true,
    },

    stateRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "State",
      required: true,
      index: true,
    },

    //////////////////////////////////////////////////////////
    // 🔥 DISTRICT (MANDATORY — FIXED)
    //////////////////////////////////////////////////////////

    districtRef: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "District",
      required: true,
      index: true,
    },

    //////////////////////////////////////////////////////////
    // 🌐 GEO MAPPING
    //////////////////////////////////////////////////////////

    admin2Code: {
      type: String,
      default: null,
      index: true,
    },

    //////////////////////////////////////////////////////////
    // 3️⃣ BUSINESS CONTROL
    //////////////////////////////////////////////////////////

    launchStatus: {
      type: String,
      enum: ["PRE_LAUNCH", "ACTIVE", "PAUSED"],
      default: "PRE_LAUNCH",
    },

    isServiceable: {
      type: Boolean,
      default: false,
    },

    onboardingEnabled: {
      type: Boolean,
      default: true,
    },

    priority: {
      type: Number,
      default: 0,
    },

    activeSalonCount: {
      type: Number,
      default: 0,
      min: 0,
    },

    //////////////////////////////////////////////////////////////
    // 🔥 HQ + AUTO FLAGS (CRITICAL)
    //////////////////////////////////////////////////////////////

    isDistrictHQ: {
      type: Boolean,
      default: false,
      index: true,
    },
    
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },

    //////////////////////////////////////////////////////////
    // ⭐ CITY TYPE
    //////////////////////////////////////////////////////////

    cityType: {
      type: String,
      enum: ["METRO", "TIER1", "TIER2", "TIER3", "TOWN", "VILLAGE"],
      default: "TIER2",
    },

    //////////////////////////////////////////////////////////
    // ⭐ CAPACITY CONTROL
    //////////////////////////////////////////////////////////

    maxSalonCapacity: {
      type: Number,
      default: 5000,
      min: 1,
    },

    //////////////////////////////////////////////////////////
    // 4️⃣ GEO (STRICT)
    //////////////////////////////////////////////////////////

    geo: {
      type: {
        type: String,
        enum: ["Point"],
        required: true,
      },
      coordinates: {
        type: [Number],
        required: true,
        validate: {
          validator: function (value) {
            if (!Array.isArray(value) || value.length !== 2) return false;

            const [lng, lat] = value;

            return (
              typeof lng === "number" &&
              typeof lat === "number" &&
              lng >= -180 &&
              lng <= 180 &&
              lat >= -90 &&
              lat <= 90
            );
          },
          message: "Invalid geo coordinates",
        },
      },
    },

    //////////////////////////////////////////////////////////
    // 5️⃣ SYSTEM FLAGS
    //////////////////////////////////////////////////////////

    isActive: {
      type: Boolean,
      default: true,
      index: true,
    },

    isDeleted: {
      type: Boolean,
      default: false,
      index: true,
    },

    notes: {
      type: String,
      default: null,
      maxlength: 500,
    },

    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },

    updatedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      default: null,
    },
  },
  {
    timestamps: true,
  }
);

//////////////////////////////////////////////////////////////
// 🔥 AUTO NORMALIZATION + SLUG + ALIASES
//////////////////////////////////////////////////////////////

CitySchema.pre("validate", function (next) {
  if (this.name) {
    this.normalizedName = this.name
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "");

    if (!this.slug) {
      this.slug = this.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-|-$/g, "");
    }
  }

  if (this.aliases && this.aliases.length > 0) {
    this.normalizedAliases = [
      ...new Set(
        this.aliases.map((a) =>
          a.toLowerCase().replace(/[^a-z0-9]/g, "")
        )
      ),
    ];
  }

  next();
});


//////////////////////////////////////////////////////////////
// 🔒 PRE-SAVE VALIDATION (ADD THIS HERE)
//////////////////////////////////////////////////////////////

CitySchema.pre("save", function (next) {
  if (!this.geo || !this.geo.coordinates) {
    return next(new Error("Geo required"));
  }

  if (!this.districtRef || !this.stateRef) {
    return next(new Error("District & State required"));
  }

  next();
});

//////////////////////////////////////////////////////////////
// 🔐 UNIQUE INDEXES
//////////////////////////////////////////////////////////////


CitySchema.index(
  { code: 1, stateRef: 1 },
  {
    unique: true,
    partialFilterExpression: {
      isDeleted: false,
      code: { $ne: null },
    },
  }
);

CitySchema.index(
  { districtRef: 1, isDistrictHQ: 1 },
  {
    unique: true,
    partialFilterExpression: {
      isDistrictHQ: true,
      isDeleted: false,
    },
  }
);

CitySchema.index(
  { normalizedName: 1, districtRef: 1 },
  {
    unique: true,
    partialFilterExpression: {
      isDeleted: false,
    },
  }
);

//////////////////////////////////////////////////////////////
// ⚡ PERFORMANCE INDEXES
//////////////////////////////////////////////////////////////

CitySchema.index({
  countryRef: 1,
  stateRef: 1,
  launchStatus: 1,
  isServiceable: 1,
  onboardingEnabled: 1,
  isActive: 1,
  isDeleted: 1,
});

CitySchema.index({
  districtRef: 1,
  isActive: 1,
  isDeleted: 1,
});

CitySchema.index({
  cityType: 1,
  isActive: 1,
  isDeleted: 1,
});

CitySchema.index({
  stateRef: 1,
  isServiceable: 1,
  isActive: 1,
  isDeleted: 1,
});

CitySchema.index({
  priority: -1,
  activeSalonCount: -1,
});

//////////////////////////////////////////////////////////////
// 🔍 SEARCH INDEXES
//////////////////////////////////////////////////////////////

// 🔥 TEXT SEARCH WITH WEIGHTS
CitySchema.index(
  { name: "text", aliases: "text" },
  {
    weights: {
      name: 5,
      aliases: 2,
    },
  }
);

// 🔥 ULTRA MICRO (COMPOUND SEARCH BOOST)
CitySchema.index({
  stateRef: 1,
  normalizedName: 1,
});

//////////////////////////////////////////////////////////////
// 🌍 GEO INDEX
//////////////////////////////////////////////////////////////

CitySchema.index({
  geo: "2dsphere",
});

//////////////////////////////////////////////////////////////
// 🚀 EXPORT
//////////////////////////////////////////////////////////////

export default mongoose.models.City ||
  mongoose.model("City", CitySchema);