import dotenv from "dotenv";
dotenv.config();

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import mongoose from "mongoose";

import City from "../models/City.js";
import State from "../models/State.js";
import District from "../models/District.js";
import Country from "../models/Country.js";

//////////////////////////////////////////////////////////////
// PATH SETUP
//////////////////////////////////////////////////////////////

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const FILE_PATH = path.join(__dirname, "../data/finalCities.json");

//////////////////////////////////////////////////////////////
// CONNECT
//////////////////////////////////////////////////////////////

await mongoose.connect(process.env.MONGODB_URI);
console.log("✅ DB Connected");

//////////////////////////////////////////////////////////////
// LOAD DATA
//////////////////////////////////////////////////////////////

if (!fs.existsSync(FILE_PATH)) {
  console.error("❌ finalCities.json NOT FOUND:", FILE_PATH);
  process.exit(1);
}

const finalCities = JSON.parse(fs.readFileSync(FILE_PATH, "utf-8"));
console.log("✅ finalCities.json loaded:", finalCities.length, "districts");

//////////////////////////////////////////////////////////////
// PRELOAD
//////////////////////////////////////////////////////////////

const country = await Country.findOne({ code: "IN" }).lean();
if (!country) throw new Error("❌ Country IN not found");

const states    = await State.find({ isDeleted: false }).lean();
const districts = await District.find({ isDeleted: false }).lean();

// stateMap: code → state
const stateMap = new Map();
states.forEach((s) => stateMap.set(s.code.toUpperCase(), s));

// districtMap: normalizedName_stateId → district
const normalize = (str) =>
  str?.toLowerCase().replace(/district/g, "").replace(/city/g, "").replace(/[^a-z0-9]/g, "").trim();

const districtMap = new Map();
districts.forEach((d) => {
  const stateId = d.stateRef?.toString();
  if (!stateId) return;
  const key = normalize(d.name) + "_" + stateId;
  districtMap.set(key, d);
});

console.log(`✅ States: ${states.length} | Districts: ${districts.length}`);

//////////////////////////////////////////////////////////////
// PROCESS
//////////////////////////////////////////////////////////////

let inserted  = 0;
let skipped   = 0;
let hqLinked  = 0;

for (const entry of finalCities) {
  try {
    ////////////////////////////////////////////////////////////
    // STATE MATCH
    ////////////////////////////////////////////////////////////
    const state = stateMap.get(entry.stateCode?.toUpperCase());

    if (!state) {
      console.warn("⚠️ State not found:", entry.stateCode, entry.districtName);
      skipped++;
      continue;
    }

    ////////////////////////////////////////////////////////////
    // DISTRICT MATCH
    ////////////////////////////////////////////////////////////
    const distKey  = normalize(entry.districtName) + "_" + state._id.toString();
    const district = districtMap.get(distKey);

    if (!district) {
      console.warn("⚠️ District not found:", entry.districtName, entry.stateCode);
      skipped++;
      continue;
    }

    ////////////////////////////////////////////////////////////
    // CITIES BULK OPS
    ////////////////////////////////////////////////////////////
    const bulkOps = [];
    let hqCityName = null;

    for (const city of entry.cities) {
      if (!city.name) continue;

      const name           = city.name.trim();
      const normalizedName = normalize(name);

      // Build geo — null for HQ fallback cities
      let geo = null;

      if (
        city.latitude !== null &&
        city.longitude !== null &&
        typeof city.latitude === "number" &&
        typeof city.longitude === "number"
      ) {
        geo = {
          type: "Point",
          coordinates: [city.longitude, city.latitude],
        };
      }

      // Skip if no geo AND not HQ (non-HQ cities must have coords)
      if (!geo && !city.isHQ) {
        skipped++;
        continue;
      }

      if (city.isHQ) hqCityName = name;

      const updateDoc = {
        $set: {
          name,
          normalizedName,
          countryRef:   country._id,
          stateRef:     state._id,
          districtRef:  district._id,
          isDistrictHQ: city.isHQ || false,
          isAutoGenerated: true,
          launchStatus: "PRE_LAUNCH",
          onboardingEnabled: true,
          isActive:     true,
          isDeleted:    false,
        },
      };

      // Only set geo if available
      if (geo) {
        updateDoc.$set.geo = geo;
      }

      bulkOps.push({
        updateOne: {
          filter: {
            normalizedName,
            districtRef: district._id,
          },
          update: updateDoc,
          upsert: true,
        },
      });

      inserted++;
    }

    ////////////////////////////////////////////////////////////
    // EXECUTE BULK
    ////////////////////////////////////////////////////////////
    if (bulkOps.length > 0) {
      await City.bulkWrite(bulkOps, { ordered: false });
    }

    ////////////////////////////////////////////////////////////
    // LINK HQ → DISTRICT
    ////////////////////////////////////////////////////////////
    if (hqCityName) {
      const hqCity = await City.findOne({
        normalizedName: normalize(hqCityName),
        districtRef:    district._id,
      }).lean();

      if (hqCity) {
        await District.updateOne(
          { _id: district._id },
          { $set: { hqCityRef: hqCity._id } }
        );
        hqLinked++;
      }
    }

  } catch (err) {
    console.error("❌ Error:", entry.districtName, err.message);
    skipped++;
  }
}

//////////////////////////////////////////////////////////////
// REPORT
//////////////////////////////////////////////////////////////

const totalCities = await City.countDocuments({ isDeleted: false });

console.log("\n🎉 CITY SEED COMPLETE");
console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━");
console.log(`✅ Inserted/Updated: ${inserted}`);
console.log(`⏭️  Skipped:          ${skipped}`);
console.log(`🏙️  HQ Linked:        ${hqLinked}`);
console.log(`📦 Total in DB:      ${totalCities}`);
console.log("━━━━━━━━━━━━━━━━━━━━━━━━━━━");

await mongoose.connection.close();
console.log("🔌 DB Disconnected");